# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = "true"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.11.150", virtualbox__intnet: "net1"
    client.vm.hostname = "client"
  end

  config.vm.define "backupServer" do |backupServer|
    backupServer.vm.network "private_network", ip: "192.168.11.160", virtualbox__intnet: "net1"
    backupServer.vm.hostname = "backupServer"
    backupServer.vm.provider :virtualbox do |vb|
      needsController = false
      unless File.exist?('./sata1.vdi')
        vb.customize ['createhd', '--filename', './sata1.vdi', '--variant', 'Fixed', '--size', 2048]
        needsController =  true
      end
      vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', './sata1.vdi']
    end
  end

end

